<?php

namespace app\models;

use Yii;
use yii\db\Query;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;

/**
 * This is the model class for table "obschie".
 *
 * @property int $id
 * @property string $title
 * @property string $content
 * @property string $image
 * @property string $note
 */
class Obschie extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'obschie';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['title', 'content'], 'required'],
            [['title', 'content', 'image', 'note'], 'string'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Title',
            'content' => 'Content',
            'image' => 'Image',
            'note' => 'Note',
        ];
    }

    public static function obschieArray()
    {
        $obschieArray = (new Query())
            ->select('*')
            ->from('obschie')
            ->all();
        return $obschieArray;
    }

    public static function obschieTitle()
    {
        $questions = ArrayHelper::getColumn(self::obschieArray(), 'title');
        return $questions;
    }

    public static function renderSidebar()
    {
        foreach (self::obschieTitle() as $title) {
            echo "<ul class='nav nav-sidebar'>
                      <li><a href='#sql_" . $title . "'> " . $title . "</a></li>
                  </ul>";
        }
    }

    public static function renderTable()
    {
        foreach (self::obschieArray() as $item) {
            $title = $item['title'];
            $content = $item['content'];
            $image = $item['image'];
            $note = $item['note'];
            echo "
                <div class='obschie_faq' id='sql_" . $title . "'>
                    <h4>" . $title . "</h4>
                    <div class='obschie-content'>" . $content . "</div>
                    " . Html::img('@web/uploads/' . $image . '') . "
                    <div class='obschie-note'>.$note.</div>
                </div>
            ";
        }
    }

    public function saveImage($filename)
    {
        $this->image = $filename;
        return $this->save(false);
    }

    public function deleteImage()
    {
        $imageUploadModel = new ImageUpload();
        $imageUploadModel->deleteCurrentImage($this->image);
    }
    public function beforeDelete()
    {
        $this->deleteImage();
        return parent::beforeDelete(); // TODO: Change the autogenerated stub
    }
    public function getImage()
    {
        return ($this->image)?'/uploads/'.$this->image:Yii::getAlias('@web/uploads/').'no-image.png';
    }
}
